# -*- coding: utf-8 -*-
"""AV1 - Programação Orientada a Objeto

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iH8yY82piG75IxDOmKrfdl5sg8DIc4x1
"""

from enum import Enum

class TiposDeArquivo(Enum):
    MP3 = 1
    MP4 = 2
    PDF = 3

class ICanal:
    def enviar_mensagem(self, destinatario, mensagem):
        pass

class CanaisMensagem(ICanal):
    def __init__(self, canal):
        self.canal = canal

    def enviar_mensagem(self, destinatario, mensagem):
        print(f"Mensagem enviada pelo canal {self.canal}:")
        print(f"Destinatário: {destinatario}")
        print(f"Mensagem: {mensagem.mensagem}")
        print(f"Data Envio: {mensagem.data_envio}")
        if hasattr(mensagem, 'arquivo'):
            print(f"Arquivo: {mensagem.arquivo}")
            print(f"Tipo Arquivo: {mensagem.formato}")
        if hasattr(mensagem, 'duracao'):
            print(f"Duração: {mensagem.duracao}")

class WhatsApp(CanaisMensagem):
    def __init__(self):
        super().__init__("WhatsApp")

class Telegram(CanaisMensagem):
    def __init__(self):
        super().__init__("Telegram")

class Instagram(CanaisMensagem):
    def __init__(self):
        super().__init__("Instagram")

class Facebook(CanaisMensagem):
    def __init__(self):
        super().__init__("Facebook")

class MensagemBasica:
    def __init__(self, mensagem, data_envio):
        self.mensagem = mensagem
        self.data_envio = data_envio

class MensagemMultimidia(MensagemBasica):
    def __init__(self, mensagem, data_envio, arquivo, formato):
        super().__init__(mensagem, data_envio)
        self.arquivo = arquivo
        self.formato = formato

class Video(MensagemMultimidia):
    def __init__(self, mensagem, data_envio, arquivo, formato, duracao):
        super().__init__(mensagem, data_envio, arquivo, formato)
        self.duracao = duracao

class Factory:
    @staticmethod
    def create(canal):
        if canal == "whatsApp":
            return WhatsApp()
        elif canal == "facebook":
            return Facebook()
        else:
            return None

def main():
    whats_app_professor = WhatsApp()
    insta_aluno = Instagram()

    mensagem = MensagemBasica("Olá", "2023-12-04")
    whats_app_professor.enviar_mensagem("+5511912345678", mensagem)

    mensagem_video = Video("Olá - Mensagem de vídeo", "2023-12-04", "fim de semana.mp4", TiposDeArquivo.MP3, 60)
    insta_aluno.enviar_mensagem("+5511912345678", mensagem_video)

    mensagem_lucas = mensagem_video
    mensagem_lucas.mensagem = "Olá, Lucas Nunes!"

    facebook = Facebook()
    facebook.enviar_mensagem("usuarioDoLucas", mensagem_lucas)

    canal = Factory.create("facebook")

if __name__ == "__main__":
    main()